# markdownlint configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

default: true

# MD013 - Line length: disabled because reference files contain long grep commands
MD013: false

# MD033 - Inline HTML: disabled because README uses HTML details/summary tags
MD033: false

# MD041 - First line in file should be a top-level heading: disabled because SKILL.md starts with YAML frontmatter
MD041: false
