name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: A clear description of what went wrong.
      placeholder: Describe the bug you encountered.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
      placeholder: Describe what you expected.
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: Output of `node --version`.
      placeholder: "e.g., v22.0.0"
    validations:
      required: false

  - type: input
    id: agent
    attributes:
      label: Agent
      description: Which AI coding agent were you using?
      placeholder: "e.g., Claude Code / Cursor / Codex / Windsurf"
    validations:
      required: false

  - type: textarea
    id: output
    attributes:
      label: Relevant script output or error
      description: Paste any relevant logs, error messages, or script output.
      render: shell
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Run the audit against project X
        2. Observe finding Y
        3. ...
    validations:
      required: false
