name: Feature Request
description: Suggest a new vulnerability pattern or framework check
labels: ["enhancement"]
body:
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of feature are you requesting?
      options:
        - New vulnerability pattern
        - New framework support
        - New IaC check
        - Report improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the feature you would like.
      placeholder: Describe the feature and why it would be useful.
    validations:
      required: true

  - type: textarea
    id: example-code
    attributes:
      label: Example vulnerable code
      description: If applicable, provide an example of the vulnerable code this feature would detect.
      render: javascript
    validations:
      required: false

  - type: textarea
    id: grep-pattern
    attributes:
      label: Suggested grep pattern
      description: If you know a suitable grep pattern for detection, share it here.
      render: shell
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant links such as OWASP pages, CVE IDs, blog posts, or documentation.
      placeholder: |
        - https://owasp.org/...
        - CVE-XXXX-XXXXX
    validations:
      required: false
